# Ta Model

In [28]:
import pandas as pd
import numpy as np
from keras.models import load_model
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
from functions import sample_mean
from lists import stop_words,noise
from plots import model_plots
import string
import warnings
import os
import pickle

punctuation = set(string.punctuation)
# ohe = OneHotEncoder()

file = 'word_dict_ta.pickle'
os.chdir('/home/ubuntu/Notebooks/capstone/models')
with open(file, 'rb') as f:
    word_dict = pickle.load(f)

In [24]:
def lower_rm_punct(review):
    return np.asarray([wrd.lower() for wrd in ''.join([wrd for\
                                                       wrd in review if wrd not in punctuation]).split()])

def my_padding(review,maxlen,dictionary):
    seq = np.zeros(maxlen).astype(str)
    if len(review) > maxlen:
        for i in range(maxlen):
            seq[i] = review[i]
    else:
        for i in range(1,len(review)+1):
            seq[-i] = review[-i]
    return np.asarray([str(0) if wrd not in dictionary else str(dictionary[wrd]) for wrd in seq]).astype(int)

def transform(review,maxlen,dictionary):
    clean_review = lower_rm_punct(review)
    return my_padding(clean_review,maxlen,dictionary)

In [3]:
# X = np.vstack([transform(doc,150,word_dict) for doc in X])

In [25]:
X = 'Well, to be honest we did not have a good\
 experience here. The service was bad and the room was not very nice.' 
review_input

'Well, to be honest we did not have a good experience here. The service was bad and the room was not very nice.'

In [26]:
X = transform(X,maxlen,word_dict).reshape(1,maxlen)
filler = model_input.copy()[:]
filler[:] = 0
X = np.vstack([filler,model_input])



In [29]:
os.chdir('/home/ubuntu/Notebooks/data')
model = load_model('first_model_ta2.h5')

ResourceExhaustedError: OOM when allocating tensor with shape[62438,300] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node embedding_1_2/random_uniform/RandomUniform (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4139) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'embedding_1_2/random_uniform/RandomUniform', defined at:
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-fe95292eff1e>", line 2, in <module>
    model = load_model('first_model_ta2.h5')
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/sequential.py", line 301, in from_config
    model.add(layer)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/sequential.py", line 165, in add
    layer(x)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/layers/embeddings.py", line 109, in build
    dtype=self.dtype)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/initializers.py", line 112, in __call__
    dtype=dtype, seed=self.seed)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 4139, in random_uniform
    dtype=dtype, seed=seed)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/random_ops.py", line 247, in random_uniform
    rnd = gen_random_ops.random_uniform(shape, dtype, seed=seed1, seed2=seed2)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_random_ops.py", line 777, in random_uniform
    name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[62438,300] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node embedding_1_2/random_uniform/RandomUniform (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4139) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.



In [20]:
y_predictions = model.predict_classes(X)
y_predictions

NameError: name 'model' is not defined

In [6]:
np.unique(y_diff,return_counts=True)[1][2:5]/np.unique(y_diff,return_counts=True)[1].sum()

0.5698401883052527

# Hotel Model

In [3]:
import pandas as pd
import numpy as np
from keras.models import load_model
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import tensorflow as tf

from functions import sample_mean
from lists import stop_words,noise
from plots import model_plots
import string
import warnings
import os
import pickle

def lower_rm_punct(review):
    return np.asarray([wrd.lower() for wrd in ''.join([wrd for\
                                                       wrd in review if wrd not in punctuation]).split()])

def my_padding(review,maxlen,dictionary):
    seq = np.zeros(maxlen).astype(str)
    if len(review) > maxlen:
        for i in range(maxlen):
            seq[i] = review[i]
    else:
        for i in range(1,len(review)+1):
            seq[-i] = review[-i]
    return np.asarray([str(0) if wrd not in dictionary else str(dictionary[wrd]) for wrd in seq]).astype(int)

def transform(review,maxlen,dictionary):
    clean_review = lower_rm_punct(review)
    return my_padding(clean_review,maxlen,dictionary)

punctuation = set(string.punctuation)
file = 'word_dict.pickle'
# ohe = OneHotEncoder()
os.chdir('/home/ubuntu/Notebooks/data/ta')

ta_data = pd.read_pickle('ta_data2.pickle').replace(1.0,2.0).replace(0.0,2.0).sample(frac=.5,random_state=3)
ta_data.columns = ['index', 'id', 'offering_id', 'text', 'ratings_overall', 'language']
ta_data = ta_data[ta_data['language'] == 'en']
y = ta_data['ratings_overall'].astype(int)
ta_data = ta_data['text']

os.chdir('/home/ubuntu/Notebooks/capstone/models')
with open(file, 'rb') as f:
    word_dict = pickle.load(f)

In [4]:
ta_data = np.vstack([transform(doc,50,word_dict) for doc in ta_data])

In [44]:
np.random.seed(3)
np.random.permutation(ta_data.shape[0])

array([69459, 87425,  7702, ..., 77049, 67224, 71530])

In [5]:
np.random.seed(3)
ta_data[np.random.permutation(ta_data.shape[0])][:40000]

array([[ 112,   11,   45, ..., 1439,   21,   31],
       [  31,  105, 5493, ..., 1018, 1836,  240],
       [1585,    1,  154, ...,   20,    1,  515],
       ...,
       [   0,    0,    0, ...,   98,    4,  159],
       [   8,  246,   11, ...,   36,  126,   35],
       [  31,  397,    2, ...,  192,  379,  650]])

In [6]:
model = load_model('first_model.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [7]:
np.random.seed(3)
#y[np.random.permutation(ta_data.shape[0])]

y_predictions = model.predict_classes(ta_data[np.random.permutation(ta_data.shape[0])][:40000])

In [8]:
np.random.seed(3)
y_diff2 = (y_predictions+2) - y.values[np.random.permutation(ta_data.shape[0])[:40000].tolist()]


In [9]:
print(np.unique(y_diff2,return_counts=True)[1][2:5]/y_diff2.shape[0])
print(np.sum(np.unique(y_diff2,return_counts=True)[1][2:5]/y_diff2.shape[0]))

[0.114625 0.537525 0.2346  ]
0.88675


## Combined Model

In [13]:
file = 'word_dict_combined.pickle'

os.chdir('/home/ubuntu/Notebooks/capstone/models')
with open(file, 'rb') as f:
    word_dict1 = pickle.load(f)
    

file = 'word_dict_ta.pickle'

os.chdir('/home/ubuntu/Notebooks/capstone/models')
with open(file, 'rb') as f:
    word_dict2 = pickle.load(f)

file = 'word_dict.pickle'

os.chdir('/home/ubuntu/Notebooks/capstone/models')
with open(file, 'rb') as f:
    word_dict3 = pickle.load(f)

In [3]:
import pandas as pd
import numpy as np
from keras.models import load_model
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
from functions import sample_mean
from lists import stop_words,noise
from plots import model_plots
import string
import warnings
import os
import pickle

def lower_rm_punct(review):
    return np.asarray([wrd.lower() for wrd in ''.join([wrd for\
                                                       wrd in review if wrd not in punctuation]).split()])

def my_padding(review,maxlen,dictionary):
    seq = np.zeros(maxlen).astype(str)
    if len(review) > maxlen:
        for i in range(maxlen):
            seq[i] = review[i]
    else:
        for i in range(1,len(review)+1):
            seq[-i] = review[-i]
    return np.asarray([str(0) if wrd not in dictionary else str(dictionary[wrd]) for wrd in seq]).astype(int)

def transform(review,maxlen,dictionary):
    clean_review = lower_rm_punct(review)
    return my_padding(clean_review,maxlen,dictionary)


punctuation = set(string.punctuation)
# ohe = OneHotEncoder()

os.chdir('/home/ubuntu/Notebooks/capstone/data')
hotels = pd.read_pickle('hotels.pickle')
hotels = hotels.drop('reviews.id',axis=1)[hotels['language']=='en']
hotels['reviews.rating'] = hotels['reviews.rating'].replace(1.0,2.0).replace(0.0,2.0)
text_sample_pct = 3/3
np.random.seed(8)

# bad_examples = hotels.iloc[noise][['reviews.text','reviews.rating']]
hotel_text = hotels[['reviews.rating','reviews.text']]
hotel_text = hotel_text.reset_index().drop('index',axis=1)
hotel_text.at[18912,'reviews.rating'] = 3
hotel_text.at[29692,'reviews.rating'] = 2
hotel_text.at[7692,'reviews.rating'] = 2
hotel_text.at[24320,'reviews.rating'] = 2
hotel_text.at[8792,'reviews.rating'] = 5
hotel_text.at[18932,'reviews.rating'] = 2
hotel_text.at[26350,'reviews.rating'] = 5
hotel_text.at[32236,'reviews.rating'] = 5
hotel_text.at[26129,'reviews.rating'] = 5
hotel_text.at[26189,'reviews.rating'] = 5
hotel_text.at[7660,'reviews.rating'] = 5
hotel_text.at[18724,'reviews.rating'] = 2
hotel_text.at[7222,'reviews.rating'] = 2
hotel_text.at[18995,'reviews.rating'] = 5
hotel_text.at[25296,'reviews.rating'] = 5
hotel_text.at[28442,'reviews.rating'] = 2
hotel_text.at[14943,'reviews.rating'] = 5
hotel_text.at[8245,'reviews.rating'] = 2
hotel_text.at[26237,'reviews.rating'] = 3
hotel_text.at[16875,'reviews.rating'] = 2
hotel_text.at[23588,'reviews.rating'] = 5
hotel_text.at[29937,'reviews.rating'] = 3
hotel_text.at[1285,'reviews.rating'] = 2
hotel_text.at[29573,'reviews.rating'] = 2
hotel_text.at[29273,'reviews.rating'] = 5
hotel_text.at[8550,'reviews.rating'] = 5
hotel_text.at[8652,'reviews.rating'] = 5
hotel_text.at[1213,'reviews.rating'] = 3
hotel_text.at[30685,'reviews.rating'] = 5
hotel_text.at[28670,'reviews.rating'] = 3
hotel_text.at[14548,'reviews.rating'] = 3
hotel_text.at[32029,'reviews.rating'] = 3
hotel_text.at[11428,'reviews.rating'] = 2
hotel_text.at[16913,'reviews.rating'] = 5
hotel_text.at[23588,'reviews.rating'] = 5
hotel_text.at[30685,'reviews.rating'] = 5
hotel_text.at[28670,'reviews.rating'] = 3
hotel_text.at[14548,'reviews.rating'] = 3
hotel_text.at[32029,'reviews.rating'] = 3
hotel_text.at[11428,'reviews.rating'] = 2
hotel_text.at[16913,'reviews.rating'] = 5
hotel_text.at[16937,'reviews.rating'] = 2
hotel_text.at[21459,'reviews.rating'] = 5
hotel_text.at[32214,'reviews.rating'] = 5
hotel_text.at[29777,'reviews.rating'] = 2
hotel_text.at[24180,'reviews.rating'] = 2
hotel_text.at[19261,'reviews.rating'] = 5
hotel_text.at[18589,'reviews.rating'] = 5
hotel_text.at[3343,'reviews.rating'] = 2
hotel_text.at[26033,'reviews.rating'] = 5
hotel_text.at[29863,'reviews.rating'] = 3
hotel_text.at[30099,'reviews.rating'] = 5
hotel_text.at[11435,'reviews.rating'] = 3
hotel_text.at[18257,'reviews.rating'] = 5
hotel_text.at[19260,'reviews.rating'] = 5
hotel_text.at[8553,'reviews.rating'] = 5
hotel_text.at[17376,'reviews.rating'] = 5
hotel_text.at[11634,'reviews.rating'] = 5
hotel_text.at[11306,'reviews.rating'] = 5
hotel_text.at[18948,'reviews.rating'] = 3
hotel_text.at[9811,'reviews.rating'] = 5
hotel_text.at[9891,'reviews.rating'] = 5
hotel_text.at[25934,'reviews.rating'] = 5
hotel_text.at[16651,'reviews.rating'] = 3
hotel_text.at[24702,'reviews.rating'] = 2
hotel_text.at[26114,'reviews.rating'] = 5
hotel_text.at[18532,'reviews.rating'] = 2
hotel_text.at[30049,'reviews.rating'] = 5
hotel_text.at[7238,'reviews.rating'] = 2
hotel_text.at[14448,'reviews.rating'] = 3
hotel_text.at[18795,'reviews.rating'] = 3
hotel_text.at[3435,'reviews.rating'] = 5
hotel_text.at[7882,'reviews.rating'] = 2
hotel_text.at[24577,'reviews.rating'] = 2
hotel_text.at[6386,'reviews.rating'] = 2

file = 'word_dict_combined.pickle'
os.chdir('/home/ubuntu/Notebooks/capstone/models')
with open(file, 'rb') as f:
    word_dict = pickle.load(f)
token = Tokenizer(char_level=False,lower=True)
# tokenize = TreebankWordTokenizer()


X = hotel_text['reviews.text']
y = hotel_text['reviews.rating']
del hotels
del hotel_text
### Run cell 1 before generating X
X = np.vstack([transform(doc,150,word_dict) for doc in X])

In [4]:
os.chdir('/home/ubuntu/Notebooks/capstone/models')
model = load_model('first_model_combined.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [10]:
y_pred = model.predict_classes(X)

In [11]:
y_diff = (y_pred+2) - y
np.unique(y_diff,return_counts=True)

(array([-3., -2., -1.,  0.,  1.,  2.,  3.]),
 array([1361, 6134, 9204, 7438, 5136, 2625,  390]))

In [12]:
np.unique(y_diff,return_counts=True)[1][2:5]/y_diff.shape[0]

array([0.28505946, 0.23036422, 0.15906838])